alias k='kubectl'
alias cb='cargo build'
alias ce='cargo check'
alias cet='cargo check --tests'
alias cf='cargo fmt'
alias glog2='git log --pretty=format:"%C(auto)%h %C(blue)%ad %C(red)%d %C(reset)%s %C(green)[%an]" --date=short --graph'
alias ls='eza'
alias gl='git pull'
alias gp='git push'
alias gst='git status'
alias glog='git log --oneline --decorate --graph'
alias gcam='git commit --all --message'
alias gsw='git switch'
alias gd='git diff'
alias git-cleanup='git switch main && git branch | grep -v "main" | xargs git branch -D'
alias clauded='claude --dangerously-skip-permissions'

