[font]
  size= 16.0
  normal = { family = "Berkeley Mono", style = "Regular" }
  bold = { family = "Berkeley Mono", style = "Bold" }
  italic = { family = "Berkeley Mono", style = "Italic" }

[general]
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]
